### ISSUE TITLE
Errors in testing "it should be possible to send funds"

### ISSUE THREAD

**Issue by vasilevskykv** [bodrovis-learning/Solidity-YT-Series#2]
When I run "npx hardhat test" I see an error
**Payments**
       should be possible to send funds:
     **TypeError: account.getAddress is not a function**
      at getAddressOf (node_modules\@nomicfoundation\hardhat-chai-matchers\src\internal\misc\account.ts:19:20)
      at Proxy.<anonymous> (node_modules\@nomicfoundation\hardhat-chai-matchers\src\internal\changeEtherBalance.ts:38:21)
      at Proxy.methodWrapper (node_modules\chai\lib\chai\utils\addMethod.js:57:25)
      at doAsserterAsyncAndAddThen (node_modules\chai-as-promised\lib\chai-as-promised.js:289:22)
      at Proxy.<anonymous> (node_modules\chai-as-promised\lib\chai-as-promised.js:255:20)
      at Proxy.overwritingMethodWrapper (node_modules\chai\lib\chai\utils\overwriteMethod.js:78:33)
      at Context.<anonymous> (test\Payments.test.js:31:15)

As I understood, the problem is with **[acc1, acc2] = await ethers.getSigners()**. There is no access to accounts which can be seen using **npx hardhat node**. Version of hardhat is 2.13.0.

**Comment by vasilevskykv** [comment]
I solved the problem making the following in **beforeEach**:

        **accounts = await ethers.getSigners()
        acc1 = accounts[1]
        acc2 = accounts[2]**

**Comment by bodrovis** [comment]
Seems like a bug with `changeEtherBalance`. https://github.com/TrueFiEng/Waffle/issues/567
